#!/bin/bash

# try to keep users from running  the wrong script
ENV="$(uname)"
if [ $ENV != "Linux" ]
  then echo "this setup script is meant for WSL only"
  exit
fi

# ensure the user ran the script as root
if [ "$EUID" -ne 0 ]
  then echo "please run as root"
  exit
fi

# ensure the environment is updated
echo "running apt-get update..."
apt-get -qq update

echo "running apt-get upgrade..."
apt-get -qq upgrade

# install basic packages that are bound to be used
echo "installing standard packages..."
apt-get -qq install \
  python3 \
  python3-pip \
  curl \
  vim \
  ca-certificates \
  zsh \
  sl \
  npm

# install and setup oh-my-zsh
cd
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "installing custom themes"
mkdir -p ~/zsh_env/

# install ls theme
curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/zsh_env/.dircolors

# install zsh theme and fonts
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
git clone https://github.com/powerline/fonts.git ~/zsh_env/

# install zsh plugin(s)
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# copy shell files
echo "copying .*rc files"
cd $OLDPWD
cp setup_files/* ~

# install vim plugin(s)
cd
mkdir -p .vim/plugin/
mv auto-pairs.vim .vim/plugin

echo "this script is complete..."
echo "please alter the first line of ~/.zshrc to match your windows username"
echo "also, please run ./powershell_setup to install the fonts you will need"
